version: '2.1'
services: 
  database:
    image: mariadb:10.3.9-bionic
    environment:
      - MYSQL_ROOT_PASSWORD=<root-password>
    volumes:
      - "<database-location>:/var/lib/mysql"
    ports:
      - "3306:3306"
    logging:
      options:
        max-size: "2000k"
        max-file: "10"
    networks:
      database-net:
        ipv4_address: 172.22.238.5
        ipv6_address: 2033:3984:3989::5
  web:
    image: nginx:1.14.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.d/sandbox-reverse-proxy.conf:/etc/nginx/conf.d/site.conf
      - ./nginx.d/partial-reverse-proxy-default.conf:/etc/nginx/partials/partial-reverse-proxy-default.conf
    logging:
      options: 
        max-size: "1000k"
        max-file: "3"
    networks:
      database-net:
        ipv4_address: 172.22.238.7
  site1web:
    image: nginx:1.14.2-alpine
    volumes:
      - /home/magento/web:/main/www/magento/web
      - ./nginx.d/sandbox-localmagento.conf:/etc/nginx/conf.d/site.conf
      - ./nginx.d/partial-magento-settings.conf:/etc/nginx/partials/partial-magento-settings.conf
    links:
      - site1php
    logging:
      options: 
        max-size: "1000k"
        max-file: "3"
    networks:
      database-net:
        ipv4_address: 172.22.238.10
  site1php:
    image: magentophp:7.1.26-fpm-alpine3.9-m2
    volumes:
      - /home/magento/web:/main/www/magento/web
      - ./php-fpm-alpine.d/magento.www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm-alpine.d/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm-alpine.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    logging:
      options: 
        max-size: "1000k"
        max-file: "3"
    networks:
      database-net:
        ipv4_address: 172.22.238.11
  site1redis:
    image: redis:4.0.11-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.d/data:/data
      - ./redis.d/redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      options: 
        max-size: "1000k"
        max-file: "3"
    networks:
      database-net:
        ipv4_address: 172.22.238.12
networks:
  database-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.22.238.0/24
        gateway: 172.22.238.1
      - subnet: 2033:3984:3989::/64
        gateway: 2033:3984:3989::1